import React, { useState, useMemo, useEffect, useCallback, useReducer } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { FiX, FiTruck, FiMapPin, FiDollarSign, FiAlertCircle, FiUser } from 'react-icons/fi';

const generateTripId = () => null; // generated by backend

const initialForm = {
  tripId: null,
  tripStatus: 'Planned',

  // Section 1
  tripDate: '',
  truckNo: '',

  // Auto-filled
  driver: '',
  driverContact: '',
  supervisor: '',
  supervisorId: '',
  sourcePlant: '',
  fuelType: '',
  mileage: 0,
  tankCapacity: 0,
  vehicleId: '',
  driverId: '',
  stationId: '',

  // Section 3
  destination: '',
  estDistance: '',
  startOdometer: '',
  lastOdometer: 0,

  // Section 4
  driverAdvance: '',
  hamaliAdvance: '',
  otherAdvance: '',

  // Extra fields kept for DB payload
  source: '',
  truckWarnings: [],
  draftSaved: false,
  lastDraftTime: null,
};

const formReducer = (state, action) => {
  switch (action.type) {
    case 'UPDATE_FIELD':
      return { ...state, [action.field]: action.value };
    case 'UPDATE_MULTIPLE':
      return { ...state, ...action.payload };
    case 'AUTO_FILL_VEHICLE': {
      const v = action.vehicle;
      if (!v) return state;
      const warnings = [];
      if (v.vehicle_status !== 'Active') warnings.push('⚠️ Vehicle not available');
      return {
        ...state,
        driver: v.driver_name || '',
        driverContact: v.driver_contact || '',
        supervisor: v.supervisor_name || '',
        supervisorId: v.supervisor_id || '',
        sourcePlant: v.source_plant || '',
        source: v.source_plant || '',
        fuelType: v.fuel_type || '',
        tankCapacity: v.gvw || 0,
        mileage: v.mileage || 0,
        lastOdometer: v.initial_odometer || 0,
        vehicleId: v.id,
        driverId: v.assigned_driver || '',
        stationId: v.station_id || '',
        truckWarnings: warnings,
      };
    }
    case 'SAVE_DRAFT':
      return { ...state, draftSaved: true, lastDraftTime: new Date().toLocaleTimeString() };
    default:
      return state;
  }
};

const inp = 'w-full px-3 py-2.5 border border-slate-200 rounded-lg text-sm bg-white focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 outline-none transition';
const inpDisabled = 'w-full px-3 py-2.5 border border-slate-200 rounded-lg text-sm bg-slate-100 text-slate-600 cursor-not-allowed';
const inpCalc = 'w-full px-3 py-2.5 border border-indigo-200 rounded-lg text-sm bg-indigo-50 text-indigo-900 font-semibold';
const lbl = 'block text-xs font-semibold text-slate-600 uppercase tracking-wide mb-1.5';
const errCls = 'text-xs text-red-500 mt-1 flex items-center gap-1';

const Sec = ({ num, icon: Icon, title, children }) => (
  <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
    <div className="flex items-center gap-3 mb-4 pb-3 border-b border-slate-100">
      <div className="w-8 h-8 rounded-full bg-indigo-50 text-indigo-600 flex items-center justify-center text-sm font-bold">{num}</div>
      <Icon className="w-4 h-4 text-indigo-600" />
      <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wide">{title}</h3>
    </div>
    {children}
  </div>
);

export default function TripAdd() {
  const navigate = useNavigate();
  const { id: draftId } = useParams();
  const [form, dispatch] = useReducer(formReducer, () => {
    const saved = localStorage.getItem('tripFormDraft');
    const parsed = saved ? JSON.parse(saved) : {};
    return { ...initialForm, ...parsed, tripId: parsed.tripId || null, proofFiles: [] };
  });
  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [vehicles, setVehicles] = useState([]);
  const [supervisorWallet, setSupervisorWallet] = useState(null);
  const [vehicleAvailability, setVehicleAvailability] = useState(null);
  const [toast, setToast] = useState(null);

  const showToast = (msg) => { setToast(msg); setTimeout(() => setToast(null), 2500); };

  // Fetch vehicles on mount
  useEffect(() => {
    fetch('http://localhost:5001/api/vehicles')
      .then(r => r.json()).then(d => d.success && setVehicles(d.data))
      .catch(() => {});
  }, []);

  // Auto-fill when truck selected
  useEffect(() => {
    if (!form.truckNo) { setVehicleAvailability(null); setSupervisorWallet(null); return; }
    Promise.all([
      fetch(`http://localhost:5001/api/vehicles/by-number/${form.truckNo}`).then(r => r.json()),
      fetch(`http://localhost:5001/api/vehicles/availability/${form.truckNo}`).then(r => r.json()),
    ]).then(([detail, avail]) => {
      if (detail.success && detail.data) {
        const v = detail.data;
        dispatch({
          type: 'AUTO_FILL_VEHICLE',
          vehicle: {
            id: v.id, driver_name: v.driver_name, driver_contact: v.driver_contact,
            supervisor_name: v.supervisor_name, supervisor_id: v.supervisor_id,
            source_plant: v.source_plant, initial_odometer: v.initial_odometer,
            fuel_type: v.fuel_type, gvw: v.gvw, mileage: v.mileage,
            assigned_driver: v.assigned_driver, station_id: v.station_id,
            vehicle_status: v.vehicle_status,
          }
        });
        // Fetch supervisor wallet balance
        if (v.supervisor_id) {
          fetch(`http://localhost:5001/api/supervisors`)
            .then(r => r.json())
            .then(d => {
              if (d.success) {
                const sup = d.data.find(s => s.id === v.supervisor_id);
                setSupervisorWallet(sup?.wallet_balance ?? null);
              }
            }).catch(() => {});
        }
      }
      if (avail.success) setVehicleAvailability(avail);
    }).catch(() => {});
  }, [form.truckNo]);

  // Load draft
  useEffect(() => {
    if (!draftId) return;
    fetch(`http://localhost:5001/api/trips/${draftId}`)
      .then(r => r.json()).then(data => {
        if (!data.success) return;
        const t = data.data;
        dispatch({
          type: 'UPDATE_MULTIPLE', payload: {
            tripId: t.trip_id, tripDate: t.trip_date ? t.trip_date.split('T')[0] : '',
            truckNo: t.truck_no || '', driver: t.driver_name || '',
            driverContact: t.driver_contact || '', supervisor: t.supervisor_name || '',
            sourcePlant: t.source_plant || '', fuelType: t.fuel_type || '',
            destination: t.destination || '', estDistance: t.est_distance || '',
            startOdometer: t.start_odometer || '', lastOdometer: t.last_odometer || 0,
            driverAdvance: t.driver_advance || '', hamaliAdvance: t.hamali_advance || '',
            otherAdvance: t.other_advance || '',
            vehicleId: t.vehicle_id || '', driverId: t.driver_id || '',
            supervisorId: t.supervisor_id || '', stationId: t.station_id || '',
          }
        });
      }).catch(() => {});
  }, [draftId]);

  const handleChange = useCallback((e) => {
    const { name, value } = e.target;
    dispatch({ type: 'UPDATE_FIELD', field: name, value });
    if (errors[name]) setErrors(p => ({ ...p, [name]: '' }));
  }, [errors]);

  const odometerDelta = useMemo(() => {
    if (!form.startOdometer || !form.lastOdometer) return null;
    return +form.startOdometer - form.lastOdometer;
  }, [form.startOdometer, form.lastOdometer]);

  const totalAdvance = useMemo(() =>
    (+form.driverAdvance || 0) + (+form.hamaliAdvance || 0) + (+form.otherAdvance || 0),
    [form.driverAdvance, form.hamaliAdvance, form.otherAdvance]);

  const validate = useCallback(() => {
    const err = {};
    if (!form.tripDate) err.tripDate = 'Trip date is required';
    if (!form.truckNo) err.truckNo = 'Select a truck';
    if (!form.destination) err.destination = 'Destination is required';
    if (!form.startOdometer) err.startOdometer = 'Start odometer is required';
    if (form.startOdometer && +form.startOdometer <= form.lastOdometer)
      err.startOdometer = `Must be > last KM (${(form.lastOdometer || 0).toLocaleString()})`;
    if (vehicleAvailability && !vehicleAvailability.available)
      err.truckNo = vehicleAvailability.message || 'Vehicle not available';
    // Block if advance exceeds supervisor wallet
    const adv = (+form.driverAdvance || 0) + (+form.hamaliAdvance || 0) + (+form.otherAdvance || 0);
    if (supervisorWallet !== null && adv > supervisorWallet)
      err.advance = `Total advance ₹${adv.toLocaleString('en-IN')} exceeds supervisor wallet ₹${Number(supervisorWallet).toLocaleString('en-IN')}`;
    setErrors(err);
    return Object.keys(err).length === 0;
  }, [form, vehicleAvailability, supervisorWallet]);

  useEffect(() => {
    const t = setTimeout(() => validate(), 300);
    return () => clearTimeout(t);
  }, [form, validate]);

  const buildPayload = (status) => ({
    trip_status: status,
    trip_type: 'Regular', trip_priority: 'Normal', transport_type: 'Outbound',
    vehicle_id: form.vehicleId || null, driver_id: form.driverId || null,
    supervisor_id: form.supervisorId || null, station_id: form.stationId || null,
    truck_no: form.truckNo || null, trip_date: form.tripDate || null,
    driver_name: form.driver || null, driver_contact: form.driverContact || null,
    supervisor_name: form.supervisor || null, source_plant: form.sourcePlant || null,
    fuel_type: form.fuelType || null, start_odometer: form.startOdometer || null,
    last_odometer: form.lastOdometer || 0, source: form.sourcePlant || null,
    destination: form.destination || null, est_distance: form.estDistance || null,
    driver_advance: +form.driverAdvance || 0, hamali_advance: +form.hamaliAdvance || 0,
    other_advance: +form.otherAdvance || 0,
    truck_warnings: JSON.stringify(form.truckWarnings || []),
    last_draft_time: new Date().toISOString().slice(0, 19).replace('T', ' '),
  });

  const handleSubmit = async () => {
    if (!validate()) return;
    setIsSubmitting(true);
    try {
      const res = await fetch('http://localhost:5001/api/trips', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(buildPayload('Planned')),
      });
      const result = await res.json();
      if (result.success) {
        localStorage.removeItem('tripFormDraft');
        showToast('✅ Trip created successfully!');
        setTimeout(() => navigate(`/trips/${result.data.trip_id}`), 1500);
      } else { alert('Failed: ' + result.message); }
    } catch { alert('Could not connect to backend.'); }
    finally { setIsSubmitting(false); }
  };

  const handleSaveDraft = async () => {
    try {
      const isValid = validate();
      const res = await fetch(
        draftId ? `http://localhost:5001/api/trips/${draftId}` : 'http://localhost:5001/api/trips',
        { method: draftId ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(buildPayload(isValid ? 'Planned' : 'Draft')) }
      );
      const result = await res.json();
      if (result.success) {
        localStorage.removeItem('tripFormDraft');
        showToast('💾 Draft saved!');
        setTimeout(() => navigate('/trips?tab=drafts'), 1500);
      }
    } catch { alert('Could not connect to backend.'); }
  };

  const isFormValid = () =>
    form.tripDate && form.truckNo && form.destination && form.startOdometer &&
    +form.startOdometer > form.lastOdometer && Object.keys(errors).length === 0;


  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
      <div className="relative bg-slate-50 rounded-2xl shadow-2xl w-full max-w-3xl max-h-[90vh] flex flex-col">

        {toast && (
          <div className="fixed top-5 left-1/2 -translate-x-1/2 z-[60] px-6 py-3.5 bg-green-600 text-white text-sm font-semibold rounded-xl shadow-xl">
            {toast}
          </div>
        )}

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 bg-white border-b border-slate-200 rounded-t-2xl">
          <div>
            <h2 className="text-xl font-bold text-slate-900">{draftId ? 'Resume Draft Trip' : 'Generate New Trip'}</h2>
            <p className="text-sm text-slate-500 mt-0.5">
              {draftId ? <span className="font-semibold text-indigo-600">Draft: {draftId}</span> : <span className="text-slate-400">Trip ID will be assigned on creation</span>}
            </p>
          </div>
          <button onClick={() => navigate('/trips')} className="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition">
            <FiX className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-6 py-5 space-y-5">

          {/* Section 1 – Date & Truck */}
          <Sec num={1} icon={FiTruck} title="Date & Truck">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className={lbl}>Trip Date <span className="text-red-500">*</span></label>
                <input type="date" name="tripDate" value={form.tripDate} onChange={handleChange} className={errors.tripDate ? `${inp} border-red-300` : inp} />
                {errors.tripDate && <div className={errCls}><FiAlertCircle className="w-3 h-3" />{errors.tripDate}</div>}
              </div>
              <div>
                <label className={lbl}>Select Truck <span className="text-red-500">*</span></label>
                <select name="truckNo" value={form.truckNo} onChange={handleChange} className={errors.truckNo ? `${inp} border-red-300` : inp}>
                  <option value="">— Select Truck —</option>
                  {vehicles.map(v => <option key={v.id} value={v.vehicle_no}>{v.vehicle_no}</option>)}
                </select>
                {errors.truckNo && <div className={errCls}><FiAlertCircle className="w-3 h-3" />{errors.truckNo}</div>}
                {vehicleAvailability && form.truckNo && (
                  vehicleAvailability.available && (vehicleAvailability.vehicleStatus || '').toLowerCase() === 'active' ? (
                    <div className="mt-1.5 flex items-center gap-1.5 text-xs text-green-700 bg-green-50 border border-green-200 rounded-lg px-3 py-2">
                      <span className="w-2 h-2 rounded-full bg-green-500" /> Vehicle available
                    </div>
                  ) : !vehicleAvailability.available ? (
                    <div className="mt-1.5 text-xs text-red-700 bg-red-50 border border-red-200 rounded-lg px-3 py-2">
                      🚫 Vehicle on active trip: {vehicleAvailability.activeTrip?.trip_id}
                    </div>
                  ) : (
                    <div className="mt-1.5 text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded-lg px-3 py-2">
                      ⚠️ Status: {vehicleAvailability.vehicleStatus}
                    </div>
                  )
                )}
              </div>
            </div>
          </Sec>

          {/* Section 2 – Auto-filled Info */}
          {form.truckNo && (
            <Sec num={2} icon={FiUser} title="Driver / Supervisor / Plant (Auto-filled)">
              {form.truckWarnings?.length > 0 && (
                <div className="mb-3 bg-amber-50 border border-amber-200 rounded-lg p-3 space-y-1">
                  {form.truckWarnings.map((w, i) => <div key={i} className="text-sm text-amber-800">{w}</div>)}
                </div>
              )}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <label className={lbl}>Driver</label>
                  <input value={form.driver} disabled className={inpDisabled} />
                </div>
                <div>
                  <label className={lbl}>Driver Contact</label>
                  <input value={form.driverContact} disabled className={inpDisabled} />
                </div>
                <div>
                  <label className={lbl}>Supervisor</label>
                  <input value={form.supervisor} disabled className={inpDisabled} />
                </div>
                <div>
                  <label className={lbl}>Source Plant</label>
                  <input value={form.sourcePlant} disabled className={inpDisabled} />
                </div>
                <div>
                  <label className={lbl}>Fuel Type</label>
                  <input value={form.fuelType} disabled className={inpDisabled} />
                </div>
                <div>
                  <label className={lbl}>Supervisor Wallet Balance</label>
                  <div className={supervisorWallet !== null
                    ? `${inpCalc} ${supervisorWallet < 1000 ? '!border-red-300 !bg-red-50 !text-red-800' : ''}`
                    : inpDisabled}>
                    {supervisorWallet !== null
                      ? `₹${Number(supervisorWallet).toLocaleString('en-IN')}`
                      : 'N/A'}
                  </div>
                  {supervisorWallet !== null && supervisorWallet < 1000 && (
                    <div className="text-xs text-red-600 mt-1">⚠️ Low wallet balance</div>
                  )}
                </div>
              </div>
            </Sec>
          )}

          {/* Section 3 – Destination & Odometer */}
          <Sec num={3} icon={FiMapPin} title="Destination & Odometer">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className={lbl}>Destination <span className="text-red-500">*</span></label>
                <input type="text" name="destination" value={form.destination} onChange={handleChange}
                  placeholder="e.g. Mumbai" className={errors.destination ? `${inp} border-red-300` : inp} />
                {errors.destination && <div className={errCls}><FiAlertCircle className="w-3 h-3" />{errors.destination}</div>}
              </div>
              <div>
                <label className={lbl}>Distance (KM)</label>
                <input type="number" name="estDistance" value={form.estDistance} onChange={handleChange}
                  placeholder="e.g. 450" className={inp} />
              </div>
              <div>
                <label className={lbl}>Start Odometer (KM) <span className="text-red-500">*</span></label>
                <input type="number" name="startOdometer" value={form.startOdometer} onChange={handleChange}
                  placeholder="Enter current reading" className={errors.startOdometer ? `${inp} border-red-300` : inp} />
                {errors.startOdometer && <div className={errCls}><FiAlertCircle className="w-3 h-3" />{errors.startOdometer}</div>}
              </div>
              <div>
                <label className={lbl}>Last Recorded KM</label>
                <div className={`${inpDisabled} flex items-center justify-between`}>
                  <span>{(form.lastOdometer || 0).toLocaleString()} km</span>
                  {odometerDelta !== null && !errors.startOdometer && (
                    <span className={`font-semibold text-xs ${odometerDelta >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                      Δ {odometerDelta >= 0 ? '+' : ''}{odometerDelta.toLocaleString()} km
                    </span>
                  )}
                </div>
              </div>
            </div>
          </Sec>

          {/* Section 4 – Advances */}
          <Sec num={4} icon={FiDollarSign} title="Advances">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
              <div>
                <label className={lbl}>Driver Advance (₹)</label>
                <input type="number" name="driverAdvance" value={form.driverAdvance} onChange={handleChange} placeholder="e.g. 5000" className={inp} />
              </div>
              <div>
                <label className={lbl}>Hamali Advance (₹)</label>
                <input type="number" name="hamaliAdvance" value={form.hamaliAdvance} onChange={handleChange} placeholder="e.g. 2000" className={inp} />
              </div>
              <div>
                <label className={lbl}>Other Advance (₹)</label>
                <input type="number" name="otherAdvance" value={form.otherAdvance} onChange={handleChange} placeholder="e.g. 1000" className={inp} />
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="bg-indigo-50 border border-indigo-200 rounded-lg px-4 py-3">
                <div className="text-xs font-semibold text-indigo-600 uppercase tracking-wide">Total Advance</div>
                <div className="text-2xl font-bold text-indigo-900 mt-1">₹{totalAdvance.toLocaleString('en-IN')}</div>
              </div>
              {supervisorWallet !== null && (
                <div className={`border rounded-lg px-4 py-3 ${
                  supervisorWallet - totalAdvance < 0 ? 'bg-red-50 border-red-200' : 'bg-green-50 border-green-200'
                }`}>
                  <div className={`text-xs font-semibold uppercase tracking-wide ${
                    supervisorWallet - totalAdvance < 0 ? 'text-red-600' : 'text-green-600'
                  }`}>After Deduction</div>
                  <div className={`text-2xl font-bold mt-1 ${
                    supervisorWallet - totalAdvance < 0 ? 'text-red-900' : 'text-green-900'
                  }`}>₹{(supervisorWallet - totalAdvance).toLocaleString('en-IN')}</div>
                  <div className="text-[10px] text-slate-400 mt-0.5">
                    Wallet ₹{Number(supervisorWallet).toLocaleString('en-IN')} − Advance ₹{totalAdvance.toLocaleString('en-IN')}
                  </div>
                </div>
              )}
            </div>
            {errors.advance && (
              <div className="mt-3 flex items-center gap-2 px-4 py-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700 font-semibold">
                <FiAlertCircle className="w-4 h-4 shrink-0" /> {errors.advance}
              </div>
            )}
          </Sec>

          {/* Fuel info note */}
          <div className="bg-amber-50 border border-amber-200 rounded-xl px-4 py-3 flex items-start gap-3">
            <span className="text-lg">⛽</span>
            <div>
              <p className="text-sm font-semibold text-amber-800">Fuel entries are added after the trip starts</p>
              <p className="text-xs text-amber-600 mt-0.5">Once the trip is started, use "Add Fuel Entry" in Trip Details to record vendor, quantity, rate and upload proof.</p>
            </div>
          </div>

        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-6 py-4 bg-white border-t border-slate-200 rounded-b-2xl">
          <div className="flex gap-2">
            <button type="button" onClick={() => navigate('/trips')} disabled={isSubmitting}
              className="px-5 py-2.5 text-sm font-semibold text-slate-600 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 disabled:opacity-50 transition">
              Cancel
            </button>
            <button type="button" onClick={handleSaveDraft} disabled={isSubmitting}
              className="px-5 py-2.5 text-sm font-semibold text-indigo-600 bg-indigo-50 border border-indigo-200 rounded-lg hover:bg-indigo-100 transition">
              💾 Save Draft
            </button>
          </div>
          <button type="button" onClick={handleSubmit} disabled={!isFormValid() || isSubmitting}
            className={`px-6 py-2.5 text-sm font-semibold rounded-lg shadow-lg transition flex items-center gap-2 ${
              isFormValid() && !isSubmitting
                ? 'text-white bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700'
                : 'text-slate-400 bg-slate-200 cursor-not-allowed'
            }`}>
            {isSubmitting ? (
              <><div className="w-4 h-4 border-2 border-slate-300 border-t-white rounded-full animate-spin" />Creating...</>
            ) : '✈️ Generate Trip'}
          </button>
        </div>

      </div>
    </div>
  );
}
